package com.machinesense.service;

import com.machinesense.dto.MlPredictionResponse;
import com.machinesense.dto.SensorIngestRequest;
import com.machinesense.entity.*;
import com.machinesense.repository.MachineRepository;
import com.machinesense.repository.MaintenanceTicketRepository;
import com.machinesense.repository.PredictionRepository;
import com.machinesense.repository.SensorReadingRepository;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;

/**
 * Core pipeline: Sensor reading in -> persist -> call ML service ->
 * persist prediction -> auto-generate a maintenance ticket when risk is high.
 */
@Service
public class SensorIngestionService {

    private final MachineRepository machineRepository;
    private final SensorReadingRepository sensorReadingRepository;
    private final PredictionRepository predictionRepository;
    private final MaintenanceTicketRepository ticketRepository;
    private final MlClientService mlClientService;

    public SensorIngestionService(MachineRepository machineRepository,
                                   SensorReadingRepository sensorReadingRepository,
                                   PredictionRepository predictionRepository,
                                   MaintenanceTicketRepository ticketRepository,
                                   MlClientService mlClientService) {
        this.machineRepository = machineRepository;
        this.sensorReadingRepository = sensorReadingRepository;
        this.predictionRepository = predictionRepository;
        this.ticketRepository = ticketRepository;
        this.mlClientService = mlClientService;
    }

    @Transactional
    public Prediction ingest(SensorIngestRequest req) {
        Machine machine = machineRepository.findByMachineCode(req.machineCode)
                .orElseThrow(() -> new RuntimeException("Unknown machine: " + req.machineCode));

        SensorReading reading = new SensorReading();
        reading.setMachine(machine);
        reading.setAirTemperature(req.airTemperature);
        reading.setProcessTemperature(req.processTemperature);
        reading.setRotationalSpeed(req.rotationalSpeed);
        reading.setTorque(req.torque);
        reading.setToolWear(req.toolWear);
        reading.setVibration(req.vibration);
        reading.setCurrent(req.current);
        reading.setPressure(req.pressure);
        sensorReadingRepository.save(reading);

        MlPredictionResponse ml = mlClientService.predict(machine, reading);

        Prediction prediction = new Prediction();
        prediction.setMachine(machine);
        prediction.setSensorReading(reading);
        prediction.setFailureProbability(ml.failureProbability);
        prediction.setHealthScore(ml.healthScore);
        prediction.setRiskLevel(Prediction.RiskLevel.valueOf(ml.riskLevel));
        prediction.setPredictedFailureType(ml.predictedFailureType);
        predictionRepository.save(prediction);

        maybeCreateTicket(machine, prediction);

        return prediction;
    }

    private void maybeCreateTicket(Machine machine, Prediction prediction) {
        if (prediction.getRiskLevel() == Prediction.RiskLevel.HEALTHY) {
            return;
        }

        // avoid opening duplicate tickets while one is already active for this machine
        List<MaintenanceTicket> existing = ticketRepository.findByMachineIdOrderByCreatedAtDesc(machine.getId());
        boolean hasActiveTicket = existing.stream().anyMatch(t ->
                t.getStatus() != MaintenanceTicket.Status.COMPLETED);
        if (hasActiveTicket) {
            return;
        }

        MaintenanceTicket ticket = new MaintenanceTicket();
        ticket.setMachine(machine);
        ticket.setPrediction(prediction);
        ticket.setPriority(prediction.getRiskLevel() == Prediction.RiskLevel.CRITICAL
                ? MaintenanceTicket.Priority.CRITICAL : MaintenanceTicket.Priority.MEDIUM);
        ticket.setTitle(String.format("%s risk detected on %s (%s)",
                prediction.getRiskLevel(), machine.getName(), machine.getMachineCode()));

        String failureNote = prediction.getPredictedFailureType() != null
                ? "Predicted failure type: " + prediction.getPredictedFailureType() + ". "
                : "";
        ticket.setDescription(String.format(
                "Auto-generated by MachineSense. %sFailure probability: %.1f%%. Health score: %d/100. " +
                        "Recommended action: inspect machine and schedule preventive maintenance.",
                failureNote, prediction.getFailureProbability() * 100, prediction.getHealthScore()));

        ticketRepository.save(ticket);
    }
}
